# Generated by Django 5.0.2 on 2024-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='method_of_payment',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('fixed per month', 'fixed per month'), ('fixed per Year', 'fixed per Year'), ('lecturewise', 'lecturewise'), ('hourwise', 'hourwise')], max_length=100),
        ),
    ]
