# Generated by Django 5.0.2 on 2024-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_subject_method_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_schedule',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
    ]
