# Generated by Django 5.0.2 on 2024-05-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_daily_schedule_calculated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='institute_name',
            new_name='classes',
        ),
    ]
